Add Ntfy.sh delivery, delivery interfacing
lostkagamine/PushyFinder pull request #1
Opened 2023-03-20 02:57 UTC by Scrxtchy

In order to make the plugin more accessible, I've added an interface for deliveries and added FOSS project [ntfy](https://ntfy.sh/) as a supported service, with support for custom servers if anyone is running the server on their own hardware

![image](https://user-images.githubusercontent.com/12771982/226235826-65fc99b4-9f05-4159-a0e2-c1c40d0f994f.png)

The way I've done this is at the best of my ability, it unfortunately won't scale up very well if people were to add more services as the configuration is still contained entirely within the window class, and the deliverymanager has to redefine what enum entry points to which delivery function is used.
I'd have loved to a reference of sorts in the configuration but this is where I struggled to find a solution

2023-03-20 10:16 UTC, ry00001 commented
Oh, this is great!

We had a similar idea of supporting multiple notification services, but ran into the roadblock of generic configuration.

We would like to focus on getting configuration to be maintainable across a large variety of notification backends, however.

2023-03-20 10:46 UTC, ry00001 commented
> > roadblock of generic configuration.
> 
> the idea wouldn't be to have a generic implementation, but to delegate these out of the interface and be able to get their configuration and UI draw calls from each specific abstract class, and then see how these can be serialised back into the configuration file.
> Tried a while this morning trying to see if I could put abstract classes into a list, as this would have likely been a helpful method of dynamically making a list of deliveries, but that struggle just went back to relying on the enum

Yeah, that's exactly the idea we had when initially developing PushyFinder.

You could perhaps use a Dictionary<string, Type> where each Type member is new().

2023-03-20 13:38 UTC, ry00001 requested changes

2023-03-20 13:38 UTC, ry00001 commented on PushyFinder/Configuration.cs
> +        public string ntfyTopic { get; set; } = "";
NtfyTopic.

2023-03-20 13:38 UTC, ry00001 commented on PushyFinder/Delivery/Delivery.cs
> +                _ => throw new NotImplementedException($"Unsupported Delivery Destination {Plugin.Configuration.DeliveryService}"),
This is unreachable.

2023-03-20 13:38 UTC, ry00001 commented on PushyFinder/Impl/DutyListener.cs
> +        DeliveryManager.Deliver().Invoke($"Duty pop", $"Duty registered: '{dutyName}'.");
Why do you need to .Invoke() this? DeliveryManager should have a method that does it for you ideally.

2023-03-20 15:30 UTC, ry00001 approved these changes

2024-02-11 08:18 UTC, lostkagamine commented
This version of the UI is now very out of date, and I'll probably need to close this and roll your changes in myself. Thank you for all your work.

2024-02-11 08:18 UTC, closed without merging