Implement sane discord webhook methods
lostkagamine/PushyFinder pull request #7
Opened 2024-06-06 04:59 UTC by wolfcomp

2024-06-06 05:07 UTC, lostkagamine requested changes

2024-06-06 05:07 UTC, lostkagamine commented on PushyFinder/Delivery/PushDelivery.cs
> +public static class PushDelivery
The way I'd do this is by implementing an IDeliveryMethod interface.

2024-06-06 05:07 UTC, lostkagamine commented on PushyFinder/Discord/AllowedMentions.cs
> +    public class AllowedMentionsBuilder
Nice!

2024-06-06 05:07 UTC, lostkagamine commented on PushyFinder/Discord/Embed.cs
> +    public class EmbedBuilder
Do we need all of this?

2024-06-06 05:09 UTC, wolfcomp commented on PushyFinder/Discord/Embed.cs
> +    public class EmbedBuilder
Probably not, but included all of it just to follow the discord spec.

2024-06-06 05:28 UTC, wolfcomp commented on PushyFinder/Delivery/PushDelivery.cs
> +public static class PushDelivery
Not sure if I fully understand. Do you want me to implement 2 separate classes where only one can be used at a time?

2024-06-06 18:16 UTC, lostkagamine commented on PushyFinder/Delivery/PushDelivery.cs
> +public static class PushDelivery
Yes, that's the way I'd prefer it done.

2024-06-06 18:38 UTC, wolfcomp commented on PushyFinder/Delivery/PushDelivery.cs
> +public static class PushDelivery
I see this being a bad thing because what if people want to be able to use both services at the same time? Then that implementation wouldn't work since you would only be allowed to use once service and not both. Current implementation has guards in the async section on the delivery for validating that services are fully setup correctly before sending.

2024-06-06 18:40 UTC, wolfcomp commented on PushyFinder/Discord/Embed.cs
> +    public class EmbedBuilder
There also could be further extension to the discord methods to allow for uploading the images and having more detailed embeds with if the rest of the spec is implemented since I didn't fully include the attachments part due to it not being necessary and requires changing flow quite the bit for upload.

2024-06-06 20:42 UTC, lostkagamine commented on PushyFinder/Delivery/PushDelivery.cs
> +public static class PushDelivery
You can just keep a list of enabled delivery methods, or have an Enabled property in the class.

2024-06-07 18:28 UTC, lostkagamine approved these changes
This is great and is almost exactly how I'd have done it myself. Thank you! Looks good to me.

2024-06-07 18:28 UTC, lostkagamine commented on PushyFinder/Delivery/MasterDelivery.cs
> +            if (delivery.IsActive)
Much better, nice!

2024-06-07 18:28 UTC, merged